spring:
  application:
    name: enviro_quiz

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: enviro_quiz

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    baseline-on-migrate: true

    enabled: true
    locations: db/migration

  security:
    user:
      name: hluli
      password: hluli


server:
  port: 8083

logging:
  level:
    org.org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs